name = "cloudflare-docker-proxy"
workers_dev = true
main = "src/index.js"
compatibility_date = "2023-08-23"
routes = [
  { pattern = "docker.zxcsoft.top", custom_domain = true },
  { pattern = "quay.zxcsoft.top", custom_domain = true },
  { pattern = "gcr.zxcsoft.top", custom_domain = true },
  { pattern = "k8s-gcr.zxcsoft.top", custom_domain = true },
  { pattern = "k8s.zxcsoft.top", custom_domain = true },
  { pattern = "ghcr.zxcsoft.top", custom_domain = true },
  { pattern = "cloudsmith.zxcsoft.top", custom_domain = true },
]

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"

[vars]
MODE="production"
LOCAL_ADDRESS=""
TARGET_UPSTREAM=""

[env.dev.vars]
MODE="debug"
LOCAL_ADDRESS="http://192.168.10.102:8787"
TARGET_UPSTREAM="https://registry-1.docker.io"